apiVersion: apps/v1
kind: Deployment
metadata:
  name: minimalapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minimalapi
  template:
    metadata:
      labels:
        app: minimalapi
    spec:
      containers:
        - name: minimalapi
          image: jmsalonen/minimalapi:latest
          ports:
            - containerPort: 5555
          env:
            - name: ASPNETCORE_URLS
              value: http://+:5555
            - name: ConnectionStrings__DefaultConnection
              value: Data Source=/app/data/sqlite.db
          volumeMounts:
            - name: sqlite-storage
              mountPath: /app/data
      volumes:
        - name: sqlite-storage
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: minimalapi
spec:
  selector:
    app: minimalapi
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
  type: ClusterIP
